version: "3.6"

services:
  crescenthr-nginx:
    image: elliotjreed/www.crescenthr.co.uk
    container_name: crescenthr-nginx
    restart: always
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:crescenthr.co.uk"
      - "traefik.www.frontend.rule=Host:www.crescenthr.co.uk"
      - "traefik.protocol=h2c"
      - "traefik.port=86"

networks:
  web:
    external: true

